"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class vehicle(object):
    __slots__ = ["timestamp", "vehicle_id", "vehicle_category", "vehicle_type", "speed"]

    __typenames__ = ["int64_t", "string", "string", "string", "int64_t"]

    __dimensions__ = [None, None, None, None, None]

    def __init__(self):
        self.timestamp = 0
        self.vehicle_id = ""
        self.vehicle_category = ""
        self.vehicle_type = ""
        self.speed = 0

    def encode(self):
        buf = BytesIO()
        buf.write(vehicle._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        __vehicle_id_encoded = self.vehicle_id.encode('utf-8')
        buf.write(struct.pack('>I', len(__vehicle_id_encoded)+1))
        buf.write(__vehicle_id_encoded)
        buf.write(b"\0")
        __vehicle_category_encoded = self.vehicle_category.encode('utf-8')
        buf.write(struct.pack('>I', len(__vehicle_category_encoded)+1))
        buf.write(__vehicle_category_encoded)
        buf.write(b"\0")
        __vehicle_type_encoded = self.vehicle_type.encode('utf-8')
        buf.write(struct.pack('>I', len(__vehicle_type_encoded)+1))
        buf.write(__vehicle_type_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">q", self.speed))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != vehicle._get_packed_fingerprint():
            raise ValueError("Decode error")
        return vehicle._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = vehicle()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        __vehicle_id_len = struct.unpack('>I', buf.read(4))[0]
        self.vehicle_id = buf.read(__vehicle_id_len)[:-1].decode('utf-8', 'replace')
        __vehicle_category_len = struct.unpack('>I', buf.read(4))[0]
        self.vehicle_category = buf.read(__vehicle_category_len)[:-1].decode('utf-8', 'replace')
        __vehicle_type_len = struct.unpack('>I', buf.read(4))[0]
        self.vehicle_type = buf.read(__vehicle_type_len)[:-1].decode('utf-8', 'replace')
        self.speed = struct.unpack(">q", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if vehicle in parents: return 0
        tmphash = (0xb75f594b0b11b9c6) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if vehicle._packed_fingerprint is None:
            vehicle._packed_fingerprint = struct.pack(">Q", vehicle._get_hash_recursive([]))
        return vehicle._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", vehicle._get_packed_fingerprint())[0]

